import { FC } from "react";
import Head from "next/head";

export interface LayoutProps {}

const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex h-screen w-screen container mx-auto">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      {children}
    </div>
  );
};

export default Layout;
