import { FC } from "react";
import Head from "next/head";

export interface LayoutProps {}

const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <div className="Layout container mx-auto">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      {children}
      <style jsx>{`
        .Layout {
          margin-top: 5%;
        }
      `}</style>
    </div>
  );
};

export default Layout;
